version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT_DB=${PORT_DB}
      - PORT=${PORT}
      - HOST_DB=db
      - HOST=${HOST}
      - NODE_ENV=${NODE_ENV}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - DATABASE=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - SINCRONIZE_DB=${SINCRONIZE_DB}
    depends_on:
      db: # CAMBIO: Se añade la condición de que el servicio esté saludable
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${USERNAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # CAMBIO: Se añade el bloque 'healthcheck'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME_DB} -d ${DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: