version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT_DB=${PORT_DB}
      - PORT=${PORT}
      - HOST_DB=db
      - HOST=${HOST}
      - NODE_ENV=${NODE_ENV}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - DATABASE=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - SINCRONIZE_DB=${SINCRONIZE_DB} 