services:
  api:
    build: .
    ports:
      - "${PORT}:3000"
    cap_add:
      - SYS_ADMIN
    environment:
      - PORT_DB=${PORT_DB}
      - HOST_DB=${HOST_DB}
      - HOST=${HOST}
      - NODE_ENV=${NODE_ENV}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - DATABASE=${DATABASE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SYNCHRONIZE_DB=${SYNCHRONIZE_DB} 
      - COOLIFY_NETWORK_NAME=${COOLIFY_NETWORK_NAME}
    healthcheck:
      interval: 1m30s
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/status"]
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - db_external_network

networks:
  db_external_network:
    name: ${COOLIFY_NETWORK_NAME}
    external: true