import { MigrationInterface, QueryRunner } from "typeorm";

export class MigrationAuto1759700819210 implements MigrationInterface {
    name = 'MigrationAuto1759700819210'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP CONSTRAINT "FK_313a2480eb0a80a449c4416466e"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_22d61b85ae419744e28f5858d3a"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_c85979aba6a3d7c434348187474"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_65e7d50de64bb2f654c6d08f6fc"`);
        await queryRunner.query(`CREATE TABLE "libro" ("id" SERIAL NOT NULL, "nombre" character varying(80) NOT NULL, "estado" boolean NOT NULL, "perfil_prestamo_id" integer, "perfil_reserva_id" integer, CONSTRAINT "PK_47ec60a1186696b36e76f499516" PRIMARY KEY ("id")); COMMENT ON COLUMN "libro"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'; COMMENT ON COLUMN "libro"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'; COMMENT ON COLUMN "libro"."perfil_prestamo_id" IS 'Id y Clave Primaria de la tabla en cuestión.'; COMMENT ON COLUMN "libro"."perfil_reserva_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`CREATE TABLE "facultad" ("id" SERIAL NOT NULL, "nombre" character varying(80) NOT NULL, "abreviacion" character varying(8) NOT NULL, CONSTRAINT "PK_9543579ebfaf8962147f06a1a61" PRIMARY KEY ("id")); COMMENT ON COLUMN "facultad"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'; COMMENT ON COLUMN "facultad"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'`);
        await queryRunner.query(`CREATE TABLE "materia_carrera" ("id" SERIAL NOT NULL, "semestre" integer NOT NULL, "materia_id" integer, "carrera_id" integer, CONSTRAINT "PK_85efc5f6880e76befe53568288d" PRIMARY KEY ("id")); COMMENT ON COLUMN "materia_carrera"."materia_id" IS 'Id y Clave Primaria de la tabla en cuestión.'; COMMENT ON COLUMN "materia_carrera"."carrera_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`CREATE TABLE "carrera" ("id" SERIAL NOT NULL, "nombre" character varying(80) NOT NULL, "facultad_id" integer, CONSTRAINT "PK_0fd6015695e5bf3f8a7f9e27711" PRIMARY KEY ("id")); COMMENT ON COLUMN "carrera"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'; COMMENT ON COLUMN "carrera"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'; COMMENT ON COLUMN "carrera"."facultad_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`CREATE TABLE "extension" ("id" SERIAL NOT NULL, "actividad" character varying(80) NOT NULL, "tipo_actividad" character varying(80) NOT NULL, "maxima" integer NOT NULL, CONSTRAINT "PK_e9e7da4f1cfc826aba870c20589" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "perfil_extension" ("id" SERIAL NOT NULL, "cantidad" integer NOT NULL DEFAULT '0', "horas" integer NOT NULL DEFAULT '0', "perfilId" integer, "extensionId" integer, CONSTRAINT "PK_5ce60a7440881cf3448bfbfb72b" PRIMARY KEY ("id")); COMMENT ON COLUMN "perfil_extension"."perfilId" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`CREATE TABLE "perfil" ("id" SERIAL NOT NULL, "nombre" character varying(80) NOT NULL, "cedula_de_identidad" character varying(30) NOT NULL, "celular" character varying(30), "telefono_particular" character varying(30), "email" character varying(30), "promedio" double precision NOT NULL DEFAULT '0', "materias_aprobadas" integer NOT NULL DEFAULT '0', "materias_reprobadas" integer NOT NULL DEFAULT '0', "usuario_id" integer, "carrera_id" integer, CONSTRAINT "REL_98ee297aeb0462f198211eb02e" UNIQUE ("usuario_id"), CONSTRAINT "PK_814c50101bf1675e1f691aad2c9" PRIMARY KEY ("id")); COMMENT ON COLUMN "perfil"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'; COMMENT ON COLUMN "perfil"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'; COMMENT ON COLUMN "perfil"."carrera_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "UQ_121cc9a8edc58e21a9e0bc95e61"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "cedulaIdentidad"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "celular"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "telefonoParticular"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP CONSTRAINT "REL_313a2480eb0a80a449c4416466"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "inscripcionId"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "tuPrimeraparcial"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "tuSegundaparcial"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "tuTrabajopractico"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "tuTrabajolaboratorio"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP COLUMN "resultado"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "maxPrimeraparcial"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "maxSegundaparcial"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "maxTrabajopractico"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "maxTrabajolaboratorio"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "usuarioId"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "materiaId"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "escalaId"`);
        await queryRunner.query(`ALTER TABLE "periodo" DROP COLUMN "fechaInscripcion"`);
        await queryRunner.query(`ALTER TABLE "periodo" DROP COLUMN "fechaVigencia"`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "cedula" character varying(12) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "UQ_83ffe924cd2d60b07421bf8dfc6" UNIQUE ("cedula")`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "password" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "primera_parcial" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "segunda_parcial" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "trabajo_practico" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "trabajo_laboratorio" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "inscripcion_id" integer`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD CONSTRAINT "UQ_430081b52a880f5d563f23020ee" UNIQUE ("inscripcion_id")`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD "final" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD "nota" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD "inscripcion_id" integer`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "primera_parcial" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "segunda_parcial" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "trabajo_practico" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "trabajo_laboratorio" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "porcentaje_asistencia" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "perfil_id" integer NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "inscripcion"."perfil_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "materia_carrera_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "periodo_id" integer NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "inscripcion"."periodo_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "escala_id" integer`);
        await queryRunner.query(`ALTER TABLE "periodo" ADD "nombre" character varying(80) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "periodo"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "periodo" ADD "fecha_inscripcion" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "periodo" ADD "fecha_vigencia" date NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "usuario"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "materia" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "materia" ADD "nombre" character varying(80) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "materia"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'`);
        await queryRunner.query(`COMMENT ON COLUMN "escala"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "nombre" character varying(20) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "periodo"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "libro" ADD CONSTRAINT "FK_450a1ade7328f160162d539cbe5" FOREIGN KEY ("perfil_prestamo_id") REFERENCES "perfil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "libro" ADD CONSTRAINT "FK_a97eb34c098b351ab087dc7f71e" FOREIGN KEY ("perfil_reserva_id") REFERENCES "perfil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materia_carrera" ADD CONSTRAINT "FK_07d02af9e2ca21a4374d3d3e786" FOREIGN KEY ("materia_id") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materia_carrera" ADD CONSTRAINT "FK_4b1c41a0dc5ad8d09173a479180" FOREIGN KEY ("carrera_id") REFERENCES "carrera"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrera" ADD CONSTRAINT "FK_d41c1ca72b590b5a1a54eef9374" FOREIGN KEY ("facultad_id") REFERENCES "facultad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfil_extension" ADD CONSTRAINT "FK_de19ab49cc1f4c61de3a952617f" FOREIGN KEY ("perfilId") REFERENCES "perfil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfil_extension" ADD CONSTRAINT "FK_f37ee3313b8b3a1438c6a6e6825" FOREIGN KEY ("extensionId") REFERENCES "extension"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfil" ADD CONSTRAINT "FK_98ee297aeb0462f198211eb02e5" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfil" ADD CONSTRAINT "FK_685c18ed40c051801dba16418ed" FOREIGN KEY ("carrera_id") REFERENCES "carrera"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD CONSTRAINT "FK_430081b52a880f5d563f23020ee" FOREIGN KEY ("inscripcion_id") REFERENCES "inscripcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD CONSTRAINT "FK_32ac941018f0c576f96dc720446" FOREIGN KEY ("inscripcion_id") REFERENCES "inscripcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_241adb2637cd1ae95952ed92664" FOREIGN KEY ("perfil_id") REFERENCES "perfil"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_027d826f554dbd690bcc88df9b0" FOREIGN KEY ("materia_carrera_id") REFERENCES "materia_carrera"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_afb8fd1b49d39f88cafcfa2ddff" FOREIGN KEY ("periodo_id") REFERENCES "periodo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_1de8feda6f11657e82b29b0dd32" FOREIGN KEY ("escala_id") REFERENCES "escala"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_1de8feda6f11657e82b29b0dd32"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_afb8fd1b49d39f88cafcfa2ddff"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_027d826f554dbd690bcc88df9b0"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP CONSTRAINT "FK_241adb2637cd1ae95952ed92664"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP CONSTRAINT "FK_32ac941018f0c576f96dc720446"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP CONSTRAINT "FK_430081b52a880f5d563f23020ee"`);
        await queryRunner.query(`ALTER TABLE "perfil" DROP CONSTRAINT "FK_685c18ed40c051801dba16418ed"`);
        await queryRunner.query(`ALTER TABLE "perfil" DROP CONSTRAINT "FK_98ee297aeb0462f198211eb02e5"`);
        await queryRunner.query(`ALTER TABLE "perfil_extension" DROP CONSTRAINT "FK_f37ee3313b8b3a1438c6a6e6825"`);
        await queryRunner.query(`ALTER TABLE "perfil_extension" DROP CONSTRAINT "FK_de19ab49cc1f4c61de3a952617f"`);
        await queryRunner.query(`ALTER TABLE "carrera" DROP CONSTRAINT "FK_d41c1ca72b590b5a1a54eef9374"`);
        await queryRunner.query(`ALTER TABLE "materia_carrera" DROP CONSTRAINT "FK_4b1c41a0dc5ad8d09173a479180"`);
        await queryRunner.query(`ALTER TABLE "materia_carrera" DROP CONSTRAINT "FK_07d02af9e2ca21a4374d3d3e786"`);
        await queryRunner.query(`ALTER TABLE "libro" DROP CONSTRAINT "FK_a97eb34c098b351ab087dc7f71e"`);
        await queryRunner.query(`ALTER TABLE "libro" DROP CONSTRAINT "FK_450a1ade7328f160162d539cbe5"`);
        await queryRunner.query(`COMMENT ON COLUMN "periodo"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "nombre" character varying(35) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "escala"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`COMMENT ON COLUMN "materia"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "materia" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "materia" ADD "nombre" character varying(35) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "usuario"."id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "periodo" DROP COLUMN "fecha_vigencia"`);
        await queryRunner.query(`ALTER TABLE "periodo" DROP COLUMN "fecha_inscripcion"`);
        await queryRunner.query(`COMMENT ON COLUMN "periodo"."nombre" IS 'Se debe nombrar obligatoriamente para la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "periodo" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "escala_id"`);
        await queryRunner.query(`COMMENT ON COLUMN "inscripcion"."periodo_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "periodo_id"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "materia_carrera_id"`);
        await queryRunner.query(`COMMENT ON COLUMN "inscripcion"."perfil_id" IS 'Id y Clave Primaria de la tabla en cuestión.'`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "perfil_id"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" DROP COLUMN "porcentaje_asistencia"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "trabajo_laboratorio"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "trabajo_practico"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "segunda_parcial"`);
        await queryRunner.query(`ALTER TABLE "escala" DROP COLUMN "primera_parcial"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP COLUMN "inscripcion_id"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP COLUMN "nota"`);
        await queryRunner.query(`ALTER TABLE "examen_final" DROP COLUMN "final"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP CONSTRAINT "UQ_430081b52a880f5d563f23020ee"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "inscripcion_id"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "trabajo_laboratorio"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "trabajo_practico"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "segunda_parcial"`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" DROP COLUMN "primera_parcial"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "UQ_83ffe924cd2d60b07421bf8dfc6"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP COLUMN "cedula"`);
        await queryRunner.query(`ALTER TABLE "periodo" ADD "fechaVigencia" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "periodo" ADD "fechaInscripcion" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "escalaId" integer`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "materiaId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD "usuarioId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "maxTrabajolaboratorio" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "maxTrabajopractico" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "maxSegundaparcial" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "escala" ADD "maxPrimeraparcial" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "examen_final" ADD "resultado" integer`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "tuTrabajolaboratorio" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "tuTrabajopractico" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "tuSegundaparcial" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "tuPrimeraparcial" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD "inscripcionId" integer`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD CONSTRAINT "REL_313a2480eb0a80a449c4416466" UNIQUE ("inscripcionId")`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "email" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "telefonoParticular" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "celular" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "cedulaIdentidad" character varying(12) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "UQ_121cc9a8edc58e21a9e0bc95e61" UNIQUE ("cedulaIdentidad")`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD "nombre" character varying(35) NOT NULL`);
        await queryRunner.query(`DROP TABLE "perfil"`);
        await queryRunner.query(`DROP TABLE "perfil_extension"`);
        await queryRunner.query(`DROP TABLE "extension"`);
        await queryRunner.query(`DROP TABLE "carrera"`);
        await queryRunner.query(`DROP TABLE "materia_carrera"`);
        await queryRunner.query(`DROP TABLE "facultad"`);
        await queryRunner.query(`DROP TABLE "libro"`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_65e7d50de64bb2f654c6d08f6fc" FOREIGN KEY ("escalaId") REFERENCES "escala"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_c85979aba6a3d7c434348187474" FOREIGN KEY ("materiaId") REFERENCES "materia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscripcion" ADD CONSTRAINT "FK_22d61b85ae419744e28f5858d3a" FOREIGN KEY ("usuarioId") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resultado_parcial" ADD CONSTRAINT "FK_313a2480eb0a80a449c4416466e" FOREIGN KEY ("inscripcionId") REFERENCES "inscripcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
